// Generated by CoffeeScript 1.9.3
(function() {
  var HTMLStringifyBrunch, sysPath;

  sysPath = require('path');

  module.exports = HTMLStringifyBrunch = (function() {
    HTMLStringifyBrunch.prototype.brunchPlugin = true;

    HTMLStringifyBrunch.prototype.type = 'template';

    HTMLStringifyBrunch.prototype.extension = 'html';

    HTMLStringifyBrunch.prototype.pattern = /\.(?:html|htm)$/;

    function HTMLStringifyBrunch(config) {
      this.config = config;
      null;
    }

    HTMLStringifyBrunch.prototype.compile = function(data, path, callback) {
      var err, error, result;
      try {
        return result = "" + (JSON.stringify(data));
      } catch (_error) {
        err = _error;
        return error = err;
      } finally {
        callback(error, result);
      }
    };

    return HTMLStringifyBrunch;

  })();

}).call(this);
